# Generated by Django 5.1.4 on 2025-05-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("EGP", "Egp"), ("SAR", "Sar")], default="EGP", max_length=3
            ),
        ),
    ]
