# Generated by Django 5.1.4 on 2025-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
