# Generated by Django 5.1.4 on 2025-05-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
