# Generated by Django 5.1.4 on 2025-03-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EGP', 'Egp'), ('KSA', 'Ksa')], default='EGP', max_length=3),
        ),
    ]
