# Generated by Django 5.1.4 on 2025-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_transaction_reference_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
