# Generated by Django 5.1.4 on 2025-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="whatsapp_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
