# Generated by Django 5.1.4 on 2025-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_configuration_whatsapp_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Contact Us", "verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterField(
            model_name="review",
            name="ordering",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="slider",
            name="ordering",
            field=models.IntegerField(default=1),
        ),
    ]
