# Generated by Django 5.1.4 on 2025-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration",
            "0003_alter_contactus_options_alter_review_ordering_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="instagram",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="snapchat",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="tiktok",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="x",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="configuration",
            name="youtube",
            field=models.URLField(null=True),
        ),
    ]
