# Generated by Django 5.1.4 on 2025-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "ذكر"), ("female", "أنثى")],
                default="male",
                max_length=6,
            ),
        ),
    ]
