# Generated by Django 5.1.4 on 2025-03-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
