# Generated by Django 5.1.4 on 2025-03-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_student_options_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="address",
        ),
    ]
