# Generated by Django 5.1.4 on 2025-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('EGP', 'Egp'), ('KSA', 'Ksa')], default='EGP', max_length=3),
        ),
    ]
