# Generated by Django 5.1.4 on 2025-05-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_currency"),
        ("payments", "0002_alter_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcourse",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_courses",
                to="payments.transaction",
            ),
        ),
    ]
