# Generated by Django 5.1.4 on 2025-03-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_studentcourse_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='educationgrade',
            options={'verbose_name_plural': 'Education Grades'},
        ),
        migrations.AlterModelOptions(
            name='educationstage',
            options={'verbose_name_plural': 'Education Stages'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
    ]
