# Generated by Django 5.1.4 on 2025-06-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_studentcourse_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "1. Country", "verbose_name_plural": "Countries"},
        ),
    ]
