# Generated by Django 5.1.4 on 2025-07-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_educationstage_countries_and_more"),
        ("users", "0004_remove_student_address_remove_teacher_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "1. Countries"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "6. Courses"},
        ),
        migrations.AlterModelOptions(
            name="educationgrade",
            options={
                "verbose_name": "Education Grade",
                "verbose_name_plural": "3. Education Grades",
            },
        ),
        migrations.AlterModelOptions(
            name="educationstage",
            options={
                "verbose_name": "Education Stage",
                "verbose_name_plural": "2. Education Stages",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Lesson", "verbose_name_plural": "7. Lessons"},
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"verbose_name": "Semester", "verbose_name_plural": "4. Semesters"},
        ),
        migrations.AlterModelOptions(
            name="studentcourse",
            options={
                "verbose_name": "Student Course",
                "verbose_name_plural": "8. Student Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "Subject", "verbose_name_plural": "5. Subjects"},
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.teacher",
            ),
        ),
    ]
