# Generated by Django 5.1.4 on 2025-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_country_options_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationstage",
            name="countries",
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.IntegerField(help_text="in days"),
        ),
    ]
