# Generated by Django 5.1.4 on 2025-08-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_remove_educationstage_countries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_kamiy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_tahsili",
            field=models.BooleanField(default=False),
        ),
    ]
