# Generated by Django 5.1.4 on 2025-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_is_kamiy_course_is_tahsili"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_kamiy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_tahsili",
            field=models.BooleanField(default=False),
        ),
    ]
