# Generated by Django 5.1.4 on 2025-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('any_unique_name', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='is_valied',
            field=models.BooleanField(default=True),
        ),
    ]
