# Generated by Django 5.1.4 on 2025-03-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('any_unique_name', '0002_remove_passwordreset_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='is_valied',
        ),
    ]
